### ISSUE TITLE
README still mentions the 'fail2ban.config-pt' state

### ISSUE THREAD

**Issue by petarmaric** [saltstack-formulas/fail2ban-formula#16]
`fail2ban.config-pt` state has apparently been removed in https://github.com/saltstack-formulas/fail2ban-formula/pull/4 but the `README` file hasn't been updated to reflect this change.

**Comment by gravyboat** [comment]
Feel free to make a PR to remove it if you would like.

**Comment by aboe76** [comment]
fixed with https://github.com/saltstack-formulas/fail2ban-formula/pull/17
