### ISSUE TITLE
wrong context in ng.config

### ISSUE THREAD

**Issue by safanaj** [saltstack-formulas/fail2ban-formula#21]
Hi, here https://github.com/saltstack-formulas/fail2ban-formula/blob/master/fail2ban/ng/config.sls#L25 the config pillar dict is passed as content of Definition key, but according to https://github.com/saltstack-formulas/fail2ban-formula/blob/master/fail2ban/ng/files/config.jinja#L21 sections expected in config dict it should be passed as top config in context

**Comment by dseira** [comment]
Hi @safanaj ,

As far as I know, there is no more section than `[Definition]` in the `fail2ban.conf` file; so there is no sense on having to define explicitely the section under the `config`. The idea is to not put useless information in the pillar, keeping it as simple as possible.

Look at the main configuration file https://github.com/fail2ban/fail2ban/blob/0.11/config/fail2ban.conf in the fail2ban project.

Anyway, I will think about it.

**Comment by safanaj** [comment]
Hi @dseira, I didn't notice that, also I saw that in your pillar.example there is an example to use `[DEFAULT]` section [here](https://github.com/saltstack-formulas/fail2ban-formula/blob/master/pillar.example#L61), I am not sure about the ordering of the jails dict render in the template, but it could be a minor issue

**Comment by dseira** [comment]
The `DEFAULT` jail section is treated as a normal jail. For example, with the following pillar:

```
fail2ban:
  ng:
    jails:
      DEFAULT:
      jail1:
      jail2:
```
Will generate the following `jail.local`:
```
[jail1]
....

[jail2]
....

[DEFAULT]
....
```
But fail2ban will work correctly.
