### ISSUE TITLE
[FEATURE] Promote ng version

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/fail2ban-formula#34]
It could be nice to promote the `ng` version of this formula.

**Comment by myii** [comment]
Sounds good.  We'd need to go through the same steps as when we promoted other `ng` formulas.

**Comment by myii** [comment]
https://github.com/saltstack-formulas/template-formula/issues/21 has links to previous conversions.

**Comment by daks** [comment]
+1 for promoting ng and doing deprecation steps

**Comment by myii** [comment]
To be more helpful, it's the section:

> - [x] Investigate how the `semantic-release` (and/or the TOFS pattern?) can be used to mitigate the use of `formula:ng` states
>   - ...
>   - Most complete conversion method (in stages) done for the `php-formula`:
>       - https://github.com/saltstack-formulas/php-formula/pull/185
>       - https://github.com/saltstack-formulas/php-formula/pull/187
>       - https://github.com/saltstack-formulas/php-formula/pull/183
